### ISSUE TITLE
make a selection, click search, click other language, now cannot search.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrasemina#3]
You do the work in editor, produce any configuration, then in the configuration tab, press the button to change the language.

expected behaviour:  the existing page is presented in French with all the same tabs (or rather alternate language equivalents of the same tabs, and just the documentation changed.

what happens:  It goes back to a single editor tab, and *search/chercher* is grayed out.  one cannot see the former configuration, and cannot select a new one.   Hitting X on the subtopic menu resets to a usable state... but confusing.

**Comment by iMacadan** [comment]
FIXED - Using cookie session, user can now switch language without loosing the current config that was set in Topic, Subtopics, Accept(s) / Reject(s) and Unmatched.
