### ISSUE TITLE
The meaning of the second accept is not easily understood, need another word.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarrasemina#5]
I think with there needs to be another column...

Accept **Matching**  ..... 

And the second(last one) should be labelled
Reject  **Other**
(and you can click the existing boxes to change the first word as it already does.)

Where Other represents any items that don´t match any of the previous clauses.  or UnMatched, or ...

**Comment by iMacadan** [comment]
For more clarity, added "Click for help - ..." in each tooltip to view detailed information.
- Click for help - About
- Click for help - Filters
- Click for help - Topic (v02)
- Click for help - Subtopic
- Click for help - Accept/Reject
- Click for help - Unmatched elements

**Comment by petersilva** [comment]
OK. where can I see it?

**Comment by iMacadan** [comment]
It should be deployed today by Noureddine...

**Comment by iMacadan** [comment]
In the mean time, you can have a look on pfd...
